name: Documentation

on:
  push:
    branches:
      - main

permissions: {}  # No permissions by default. Permissions are added per-job.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          # NOTE: We use 3.10+ typing syntax via future, which pdoc only
          # understands if it's actually run with Python 3.10 or newer.
          python-version: ">= 3.10"

      - name: Enable build input caching
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ./.cache/pip
            ./.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: setup
        env:
          OUTPUT_ENV_VAR: GITHUB_OUTPUT
          PIP_CACHE_DIR: ./.cache/pip
          POETRY_CACHE_DIR: ./.cache/pypoetry
        run: |
          source ./scripts/common.sh
          assertPython
          enterVenv
          poetryInstall

      - name: build docs
        run: |
          source ./scripts/common.sh
          enterVenv
          pdoc -o ./html -d google ./pywemo/

      - name: upload docs artifact
        uses: actions/upload-pages-artifact@64bcae551a7b18bcb9a09042ddf1960979799187 # v1.0.8
        with:
          path: ./html/

  # This is copied from the official `pdoc` example:
  #   https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml
  #
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # NOTE: Needed to push to the repository.
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@af48cf94a42f2c634308b1c9dc0151830b6f190a # v2.0.1
