name: pre-commit PR check

on:
  pull_request:
    branches: 
      - main
      - pywemo_esev

permissions: {}  # No permissions needed for this workflow.

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
      with:
        python-version: 3.x
    - name: Install Poetry
      run: |
        . scripts/common.sh
        poetryInstall
    - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
    - uses: pre-commit-ci/lite-action@2529d76d2c5ffdf2a85aa090c38949eada94d39d # v1.0.1
      if: always()
