# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Push build changes

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - dependabot/**
      - pywemo_esev_pr

permissions: {}  # No permissions by default. Permissions are added per-job.

jobs:
  push:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.head_repository.full_name == github.repository &&
      github.actor == 'esev'
    permissions:
      contents: write
    steps:
      - name: Download build changes
        id: download
        uses: actions/github-script@v3.1.0
        with:
          result-encoding: string
          script: |
            const artifacts = await github.actions.listWorkflowRunArtifacts({
              ...context.repo,
              run_id: ${{github.event.workflow_run.id}},
            });
            const buildChangesArtifacts = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name.startsWith("build-changes-");
            });
            if (buildChangesArtifacts.length < 1) {
              return '';
            }
            const download = await github.actions.downloadArtifact({
              ...context.repo,
              artifact_id: buildChangesArtifacts[0].id,
              archive_format: 'zip',
            });
            await io.mkdirP('${{github.workspace}}/download');
            const fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/download/build-changes.zip', Buffer.from(download.data));
            return '${{github.workspace}}/download/build-changes.zip';
      - name: Checkout code
        if: steps.download.outputs.result
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.workflow_run.head_branch}}
          path: pywemo_checkout
      - name: Apply changes
        if: steps.download.outputs.result
        env:
          CHANGES_ZIP: ${{steps.download.outputs.result}}
        working-directory: pywemo_checkout
        run: |
          (cd $(dirname "$CHANGES_ZIP") && unzip $(basename "$CHANGES_ZIP"))
          git apply --no-add --cached "$(dirname "$CHANGES_ZIP")/build-changes.patch"
      - name: Push changes
        uses: actions/github-script@v3.1.0
        with:
          # https://github.com/orgs/community/discussions/50055
          script: |
            let output = '';
            const options = {};
            options.listeners = {
              stdout: (data) => {
                output += data.toString();
              }
            };
            options.cwd = './pywemo_checkout';
            const rc = await exec.exec('git', ['diff-index', '--cached', 'HEAD'], options);
            const treeObjs = [];
            for (let diff of output.split('\n')) {
              const [metas, name] = diff.split('\t', 1);
              console.log(name);
              const meta = metas.split(' ');
              console.log(meta);
              if (meta.length < 5 || meta[4] != 'M') continue;
              output = '';
              const rc = await exec.exec('git', ['cat-file', meta[3]], options);
              treeObjs.push({
                path: name,
                mode: meta[1],
                type: 'blob',
                content: output
              });
            }
            console.log(treeObjs);
            const tree = await github.git.createTree({
              ...context.repo,
              tree: treeObjs,
              base_tree: '${{github.event.workflow_run.head_commit.tree_id}}'
            });
            console.log(tree);
            const gitCommit = await this.octokitClient.git.createCommit({
              ...context.repo,
              message: '[dependabot skip] build changes for ${{github.event.workflow_run.head_commit.id}}',
              tree: tree.data.sha,
              parents: ['${{github.event.workflow_run.head_commit.id}}'],
            });
            console.log(gitCommit);
            const ref = await git.updateRef({
              ...context.repo,
              ref: 'refs/heads/${{github.event.workflow_run.head_branch}}',
              sha: gitCommit.data.sha,
            });
            console.log(ref);
      # - name: Push changes
      #   if: steps.download.outputs.result
      #   env:
      #     PARENT_SHA: ${{github.event.workflow_run.head_sha}}
      #   working-directory: pywemo_checkout
      #   run: |
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config user.name "github-actions[bot]"
      #     git commit -nm "[dependabot skip] build changes for $PARENT_SHA"
      #     git push
